/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProjectConfiguration } from "./ProjectConfiguration";
import { ProjectConfigurationCountArgs } from "./ProjectConfigurationCountArgs";
import { ProjectConfigurationFindManyArgs } from "./ProjectConfigurationFindManyArgs";
import { ProjectConfigurationFindUniqueArgs } from "./ProjectConfigurationFindUniqueArgs";
import { DeleteProjectConfigurationArgs } from "./DeleteProjectConfigurationArgs";
import { ProjectConfigurationService } from "../projectConfiguration.service";
@graphql.Resolver(() => ProjectConfiguration)
export class ProjectConfigurationResolverBase {
  constructor(protected readonly service: ProjectConfigurationService) {}

  async _projectConfigurationsMeta(
    @graphql.Args() args: ProjectConfigurationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProjectConfiguration])
  async projectConfigurations(
    @graphql.Args() args: ProjectConfigurationFindManyArgs
  ): Promise<ProjectConfiguration[]> {
    return this.service.projectConfigurations(args);
  }

  @graphql.Query(() => ProjectConfiguration, { nullable: true })
  async projectConfiguration(
    @graphql.Args() args: ProjectConfigurationFindUniqueArgs
  ): Promise<ProjectConfiguration | null> {
    const result = await this.service.projectConfiguration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProjectConfiguration)
  async deleteProjectConfiguration(
    @graphql.Args() args: DeleteProjectConfigurationArgs
  ): Promise<ProjectConfiguration | null> {
    try {
      return await this.service.deleteProjectConfiguration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
