/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UsageAnalytics } from "./UsageAnalytics";
import { UsageAnalyticsCountArgs } from "./UsageAnalyticsCountArgs";
import { UsageAnalyticsFindManyArgs } from "./UsageAnalyticsFindManyArgs";
import { UsageAnalyticsFindUniqueArgs } from "./UsageAnalyticsFindUniqueArgs";
import { DeleteUsageAnalyticsArgs } from "./DeleteUsageAnalyticsArgs";
import { UsageAnalyticsService } from "../usageAnalytics.service";
@graphql.Resolver(() => UsageAnalytics)
export class UsageAnalyticsResolverBase {
  constructor(protected readonly service: UsageAnalyticsService) {}

  async _usageAnalyticsItemsMeta(
    @graphql.Args() args: UsageAnalyticsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UsageAnalytics])
  async usageAnalyticsItems(
    @graphql.Args() args: UsageAnalyticsFindManyArgs
  ): Promise<UsageAnalytics[]> {
    return this.service.usageAnalyticsItems(args);
  }

  @graphql.Query(() => UsageAnalytics, { nullable: true })
  async usageAnalytics(
    @graphql.Args() args: UsageAnalyticsFindUniqueArgs
  ): Promise<UsageAnalytics | null> {
    const result = await this.service.usageAnalytics(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UsageAnalytics)
  async deleteUsageAnalytics(
    @graphql.Args() args: DeleteUsageAnalyticsArgs
  ): Promise<UsageAnalytics | null> {
    try {
      return await this.service.deleteUsageAnalytics(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
