/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CustomTemplate } from "./CustomTemplate";
import { CustomTemplateCountArgs } from "./CustomTemplateCountArgs";
import { CustomTemplateFindManyArgs } from "./CustomTemplateFindManyArgs";
import { CustomTemplateFindUniqueArgs } from "./CustomTemplateFindUniqueArgs";
import { DeleteCustomTemplateArgs } from "./DeleteCustomTemplateArgs";
import { CustomTemplateService } from "../customTemplate.service";
@graphql.Resolver(() => CustomTemplate)
export class CustomTemplateResolverBase {
  constructor(protected readonly service: CustomTemplateService) {}

  async _customTemplatesMeta(
    @graphql.Args() args: CustomTemplateCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CustomTemplate])
  async customTemplates(
    @graphql.Args() args: CustomTemplateFindManyArgs
  ): Promise<CustomTemplate[]> {
    return this.service.customTemplates(args);
  }

  @graphql.Query(() => CustomTemplate, { nullable: true })
  async customTemplate(
    @graphql.Args() args: CustomTemplateFindUniqueArgs
  ): Promise<CustomTemplate | null> {
    const result = await this.service.customTemplate(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CustomTemplate)
  async deleteCustomTemplate(
    @graphql.Args() args: DeleteCustomTemplateArgs
  ): Promise<CustomTemplate | null> {
    try {
      return await this.service.deleteCustomTemplate(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
